### ISSUE TITLE
Release可以顺便放出build好的 assetbunle 文件吗？

### ISSUE THREAD

**Issue by aprz512** [LocalizeLimbusCompany/LLC_ChineseFontAsset#4]

**Comment by N071** [comment]
啊，这边的issue似乎被邮件淹没了……现在才看到很不好意思。
我们的模组应用字体时，就是使用assetbundle文件的。我在进行commit时正是上传了我在本地打包好的ab包`assets/tmpchinesefont`。您在release下载到的zip里面应该就包含那个文件。使用AssetStudio等工具打开这个文件，其中就有跑好了的textmeshpro资源。
如果您下载了我们的模组，在plugins文件夹里应当也会有同样的ab包，这样模组才能够应用字体的。
